# Generated by Django 3.1.3 on 2021-02-25 01:36

from django.db import migrations, models
import imageSearchAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageSearchAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.CharField(default=imageSearchAPI.models.userID_default, max_length=320),
        ),
    ]
